export const TOGGLE_CHAT = 'TOGGLE_CHAT';
export const TOGGLE_INPUT_DISABLED = 'TOGGLE_INPUT_DISABLED';
export const ADD_NEW_USER_MESSAGE = 'ADD_NEW_USER_MESSAGE';
export const ADD_NEW_RESPONSE_MESSAGE = 'ADD_NEW_RESPONSE_MESSAGE';
export const ADD_NEW_LINK_SNIPPET = 'ADD_NEW_LINK_SNIPPET';
export const ADD_COMPONENT_MESSAGE = 'ADD_COMPONENT_MESSAGE';
